### ISSUE TITLE
Have travis deploy to wordpress SVN

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-wordpress-satellite-plugin#16]
I don't know how good of an idea this is or what people think but we could probably have travis deploy this to the wordpres svn for us.

**Comment by radius314** [comment]
That line of thinking... what makes this plugin more or less complex than the others in terms of deployment to svn?

**Comment by pjaudiomv** [comment]
Yea I can't remember, I see no reason why we couldn't. I feel like I didn't because I was t a big contributor or owner of repo

**Comment by pjaudiomv** [comment]
looks like I already did this on Jan 9th and Jan 14th I tagged a new release and auto deployed to wordpress
https://travis-ci.org/bmlt-enabled/bmlt-wordpress-satellite-plugin/jobs/479636191

https://github.com/bmlt-enabled/bmlt-wordpress-satellite-plugin/blame/master/.travis.yml

**Comment by radius314** [comment]
Thanks!
