### ISSUE TITLE
Add Australian Theme to future updates

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/bmlt-wordpress-satellite-plugin#20]
[Australia.zip](https://github.com/bmlt-enabled/bmlt-wordpress-satellite-plugin/files/3620150/Australia.zip)
Hi Guys,

Hoping we can add the Australian Theme into future updates.
This will save us time and allow for a smoother update process moving forward.
Thanks in advance
YILS
Bruce

**Comment by ChrisMarshallNY** [comment]
Should be quite feasible, as long as it jives with the other themes. I'd suggest providing it to @pjaudiomv

**Comment by pjaudiomv** [comment]
thanks Bruce and Chris I'll take a look

**Comment by pjaudiomv** [comment]
@brustar64 can you actually open a ticket here https://github.com/bmlt-enabled/bmlt-satellite-base-class

**Comment by pjaudiomv** [comment]
this is done and just released in `3.10.0`

**Comment by brustar64** [comment]
Thanks very much! 🙂
________________________________
