### ISSUE TITLE
Still having issues with plugin 3.9.6

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/bmlt-wordpress-satellite-plugin#8]
on mvana.org i didnt have plugin installed fo ri dont need it. I did new install of plugin settings page is there, set the root server, api key. and created a page with shortcode on it. However plugin isnt reading shortcode my page just displays shortcode

https://www.mvana.org/bmltsat/
[bmlt]

[bmlt_table]

I had a similar problem with nerna.org when updating the settings page worked but not reading shortcode. i cleared theme cache siteground cache and used private browser.

mvana is on ipage
nerna is on siteground

weird thing is when upgrading charlestonna.org which is ipage it worked fine.

**Comment by pjaudiomv** [comment]
when trying to update from 3.9.3 to 3.9.6 on sca.charlestonna.org i get the following notice and plugin just doesnt update
Constant ROOTPATH already defined in /home/charl767/chs/wp-content/plugins/bmlt-wordpress-satellite-plugin/vendor/bmlt/bmlt-satellite-base-class/bmlt-cms-satellite-plugin.php on line 32

**Comment by pjaudiomv** [comment]
on sca.charlestonna.org after deleting and reinstalling i get same warning notice but it activates, once again though not reading shortcode
https://sca.charlestonna.org/bmltsat/

**Comment by radius314** [comment]
The plugin doesn't use standard WP shortcode methodology, you must double square bracket everything.  https://bmlt.app/what-is-the-bmlt/sample-bmlt-searches/

**Comment by pjaudiomv** [comment]
omg duh, im still getting this notice with debugging turned on Notice: Constant ROOTPATH already defined in /home/charl767/chs/wp-content/plugins/bmlt-wordpress-satellite-plugin/vendor/bmlt/bmlt-satellite-base-class/bmlt-cms-satellite-plugin.php on line 32

**Comment by pjaudiomv** [comment]
and nerna.org still doesnt work, not reading shortcode idk if it is an issue with wordpress database or not but its not reading shortcode

**Comment by radius314** [comment]
doesn't work means?

**Comment by pjaudiomv** [comment]
not reading shortcode https://nerna.org/meeting-search/

**Comment by pjaudiomv** [comment]
fuck figured it out

**Comment by pjaudiomv** [comment]
I was using a stupid custom theme that wasn't baked into plugin

**Comment by pjaudiomv** [comment]
Im sorry for wasting your time, i'll submit a pr to include theme in next release so i dont go through this again

**Comment by radius314** [comment]
What theme?

**Comment by radius314** [comment]
The ROOTPATH constant thing is something worth patching.  It should have a check there to make sure it’s not already set.

**Comment by pjaudiomv** [comment]
a Color Theme I had made for the plugin, so when i updated the theme disappeared because isnt apart of the repo
