### ISSUE TITLE
ROOTPATH and dependency issues.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bmlt-wordpress-satellite-plugin#9]
Now that we are using packagist instead of git directly for composer, this can probably go away.  Doesn't make sense to fix something that doesn't even need to be there.  Also the satellite plugin doesn't (if all goes well), need to specify the bmlt-satellite-driver because the bmlt-satellite-base-class composer.json already says that.  This is more of an artifact of not using packagist.

**Comment by radius314** [comment]
This is a post 3.9.6 cleanup activity.  Not sure if this is an actual bug yet.

**Comment by radius314** [comment]
I'm pretty sure this is resolved.

**Comment by pjaudiomv** [comment]
this was def resolved....not without some pain.
